car_rental/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('drivex.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drivex/urls.py
from django.urls import path, include
from . import views

app_name = 'drivex'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

    path('car/list', views.car_filter_view, name='car-list'),
    path('car/<int:pk>', views.CarDetailView.as_view(), name='car-detail'),

    path('brand/list', views.BrandListView.as_view(), name='brand-list'),
    path('brand/<int:pk>', views.BrandDetailView.as_view(), name='brand-detail'),

    path('user/register', views.register_request, name='user-register'),
    path('user/login', views.login_request, name='user-login'),
    path('user/logout', views.logout_request, name='user-logout'),
    path('user/profile', views.update_profile, name='user-profile'),

    path('order/new/<int:pk>', views.new_order, name='new-order'),
    path('order/list', views.OrderListView.as_view(), name='order-list'),

    path('review/<int:car_pk>/add', views.add_review, name='add-review'),
    path('review/<int:car_pk>/update', views.update_review, name='update-review'),

    # path('rating/<int:car_pk>/add', views.add_car_rating, name='add-rating'),

    path('favorite/<int:car_pk>/add', views.toggle_car_favorite, name='toggle-favorite'),
    path('profile/favorites', views.favorite_list_view, name='profile-favorites'),
    path('profile/reviews', views.ReviewListView.as_view(), name='profile-reviews'),

    path('search', views.search, name='search'),

    path('api/cars', views.CarListAPIView.as_view())
]

drivex/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.db.models import Q, Avg
from datetime import datetime
from django.urls import reverse
from django.utils import timezone
from .functions import UploadToPathAndRename

date_format = "%Y-%m-%d"


brands_upload_path = UploadToPathAndRename("brands")
cars_upload_path = UploadToPathAndRename("cars")


class Brand(models.Model):
    objects = models.Manager()

    name = models.CharField(max_length=32)
    logo = models.ImageField(upload_to="brands", null=True, blank=True)
    # cars

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Feature(models.Model):
    objects = models.Manager()

    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Car(models.Model):
    SEDAN = "SD"
    HATCHBACK = "HB"
    CROSSOVER = "CR"
    TRUCK = "TR"
    CONVERTIBLE = "CN"
    BODY_STYLES = [
        (SEDAN, "Sedan"),
        (HATCHBACK, "Hatchback"),
        (CROSSOVER, "SUV & Crossover"),
        (TRUCK, "Truck & Van"),
        (CONVERTIBLE, "Convertible"),
    ]
    GAS = "GS"
    DIESEL = "DS"
    ELECTRO = "EL"
    HYBRID = "HY"

    POWER_SOURCES = [
        (GAS, "Gasoline"),
        (DIESEL, "Diesel"),
        (ELECTRO, "Electricity"),
        (HYBRID, "Hybrid"),
    ]

    AUTOMATIC = "AT"
    MANUAL = "MT"
    TRANSMISSIONS = [
        (AUTOMATIC, "Automatic"),
        (MANUAL, "Manual"),
    ]

    objects = models.Manager()
    name = models.CharField(max_length=32)
    brand = models.ForeignKey(Brand, related_name="cars", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="cars", default="cars/car.png", blank=True)
    category = models.ForeignKey(
        Category, related_name="cars", on_delete=models.SET_NULL, null=True, blank=True
    )

    style = models.CharField(max_length=2, choices=BODY_STYLES, default=SEDAN)
    power = models.CharField(max_length=2, choices=POWER_SOURCES, default=GAS)
    transmission = models.CharField(max_length=2, choices=TRANSMISSIONS, default=MANUAL)
    capacity = models.FloatField(default=1.6)  # engine capacity
    passengers = models.PositiveSmallIntegerField(default=5)
    doors = models.PositiveSmallIntegerField(default=4)
    boot_space = models.PositiveIntegerField(default=500)
    consumption = models.FloatField(default=8.0)  # litres per 100 km
    features = models.ManyToManyField(Feature, related_name="cars", blank=True)
    rating = models.FloatField(null=True, blank=True)
    badge = models.ForeignKey(
        "Badge", related_name="cars", on_delete=models.SET_NULL, null=True, blank=True
    )
    price = models.PositiveIntegerField(default=20)
    favorites = models.ManyToManyField(User, blank=True, related_name="favorites")

    def __str__(self):
        return f"{self.brand.name} {self.name}"

    def url(self):
        return reverse("drivex:car-detail", kwargs={"pk": self.id})

    def is_available(self, from_date, to_date):
        # Check if the car is available for the selected dates
        wanted_start = datetime.strptime(from_date, date_format).date()
        wanted_end = datetime.strptime(to_date, date_format).date()
        reservations = Order.objects.filter(
            car=self, status__in=[Order.ACTIVE, Order.NEW]
        )
        for reservation in reservations:
            if (reservation.date_start <= wanted_start <= reservation.date_end) or (
                wanted_end < wanted_start
            ):
                return False
            if reservation.date_start <= wanted_end <= reservation.date_end:
                return False
            if (
                wanted_start <= reservation.date_start
                and wanted_end >= reservation.date_end
            ):
                return False
        return True


class Badge(models.Model):
    VIOLET = "#7400C8"
    ORANGE = "#ff8e30"
    GREEN = "#70d628"
    BLUE = "#12bbee"
    RED = "#EA0D01"
    COLORS = [
        (VIOLET, "violet"),
        (ORANGE, "orange"),
        (GREEN, "green"),
        (BLUE, "blue"),
        (RED, "red"),
    ]

    objects = models.Manager()

    name = models.CharField(max_length=32)
    color = models.CharField(max_length=7, choices=COLORS, default=VIOLET)
    # cars

    def __str__(self):
        return self.name


class Profile(models.Model):
    objects = models.Manager()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(
        upload_to="users", default="users/user.jpg", max_length=128, blank=True
    )
    name = models.CharField(max_length=32, blank=True)
    tel = models.CharField(max_length=10, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        try:
            instance.profile.save()
        except Profile.DoesNotExist:
            Profile.objects.create(user=instance)


class Order(models.Model):
    NEW = "NW"
    ACTIVE = "AC"
    CLOSED = "CL"

    STATUSES = [
        (NEW, "New"),
        (ACTIVE, "Active"),
        (CLOSED, "Closed"),
    ]

    objects = models.Manager()

    user = models.ForeignKey(User, related_name="orders", on_delete=models.CASCADE)
    car = models.ForeignKey(Car, related_name="orders", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=True)
    date_start = models.DateField(default=timezone.now)
    date_end = models.DateField()
    status = models.CharField(max_length=2, choices=STATUSES, default=NEW)
    number = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return f"self.number"


@receiver(pre_save, sender=Order)
def add_order_number(sender, instance, *args, **kwargs):
    if not instance.number:
        date_part = timezone.now().strftime("%Y%m%d")
        last_order = (
            Order.objects.filter(number__startswith=date_part).order_by("number").last()
        )
        if not last_order:
            new_order_number = date_part + "-0001"
        else:
            last_order_number = last_order.number
            new_order_number = int(last_order_number.split("-")[-1]) + 1
            new_order_number = date_part + f"-{new_order_number:04}"
        instance.number = new_order_number


class Review(models.Model):
    objects = models.Manager()
    user = models.ForeignKey(User, related_name="reviews", on_delete=models.CASCADE)
    car = models.ForeignKey(Car, related_name="reviews", on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True)
    rate = models.PositiveSmallIntegerField(null=True, blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        rating = self.car.reviews.aggregate(Avg("rate"))["rate__avg"]
        self.car.rating = rating
        self.car.save()

    class Meta:
        ordering = ["-created"]

drivex/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import DateInput

from .models import *
from .widgets import ImagePreviewWidget, StarRatingWidget


class NewUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text="Optional.")

    class Meta:
        model = User
        fields = ("username", "first_name", "password1", "password2")


class UserForm(UserCreationForm):
    # email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "password1", "password2")


class ProfileForm(forms.ModelForm):
    tel = forms.RegexField(regex="^0\d{9}$", max_length=10, min_length=10, required=True,
                           help_text="Enter a tel number in such format 0991234567")
    name = forms.CharField(max_length=30, required=False, help_text="Optional.")
    photo = forms.ImageField(widget=ImagePreviewWidget, required=False, help_text="It will be your profile picture.")

    class Meta:
        model = Profile
        fields = ("tel", "name",  "photo",)


class OrderForm(forms.ModelForm):
    date_start = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    date_end = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = ("date_start", "date_end")


class ReviewForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea, label='Write your review')
    # rate = forms.SeleField(widget=StarRatingWidget, label='Write your review')

    class Meta:
        model = Review
        fields = ('text',)

drivex/templates/drivex/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"> {% endcomment %}
  <link href="{% static 'drivex/css/customized_bootstrap.css' %}" rel="stylesheet">
  {% block extrastyles %}{% endblock %}
  <link rel="stylesheet" href="{% static 'drivex/css/style.css' %}">
</head>
<body class="body-bg">

<nav class="navbar navbar-expand-lg shadow  bg-white py-3">
  <div class="container justify-content-between">
    <div class="d-flex">
      <a class="navbar-brand me-5" href="{% url 'drivex:home' %}">
        {% include 'drivex/parts/logo.html' %}
      </a>
      {% comment %} <a class="navbar-brand" href="{% url 'drivex:home' %}"></a> {% endcomment %}
      <div>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      </div>
      
      <div class="collapse navbar-collapse fs-5 flex-grow-0" id="navbarSupportedContent">
        {% with request.resolver_match.url_name as url_name %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item me-2">
            <a
              class="nav-link {% if url_name == 'home' %}active{% endif %}"
              href="{% url 'drivex:home' %}"
              >Home</a
            >
          </li>
          <li class="nav-item me-2">
            <a
              class="nav-link {% if url_name == 'car-list' %}active{% endif %}"
              href="{% url 'drivex:car-list' %}"
              >Cars</a
            >
          </li>
          <li class="nav-item me-2">
            <a
              class="nav-link {% if url_name == 'brands' %}active{% endif %}"
              href="{% url 'drivex:brand-list' %}"
              >Brands</a
            >
          </li>
        </ul>
        {% endwith %}
      </div>
    </div>
    <form class="d-flex me-5" role="search" action="{% url 'drivex:search' %}" method="POST">
      {% csrf_token %}
      <div class="input-group">
        <select name="search-category" class="form-select" id="CategorySelect" style="max-width: 90px">
          <option value="1" selected>All</option>
          <option value="2">Cars</option>
          <option value="3">Brands</option>
        </select>
        <input name="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
        <input type="hidden" name="next" value="{{ request.path }}">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </div>
    </form>

    <div class="user">
      <div class="d-inline-flex align-items-center">
        {% if user.is_authenticated %} 
        {% if user.profile.photo %}
          <div class="overflow-hidden rounded-circle me-2" style="width: 30px; height: 30px">
            <img class="object-fit-cover" src="{{ user.profile.photo.url }}" width="100%" height="100%" />
          </div>
        {% endif %}

        <div class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user }}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'drivex:user-profile' %}">Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'drivex:order-list' %}">Orders</a></li>
            <li><a class="dropdown-item" href="{% url 'drivex:profile-favorites' %}">Favorites</a></li>
            <li><a class="dropdown-item" href="{% url 'drivex:profile-reviews' %}">Reviews</a></li>
            <li><a class="dropdown-item" href="{% url 'drivex:user-logout' %}?next={{ request.path }}">Logout</a></li>
          </ul>
        </div>

      </div>

      {% else %}
      <a class="link-secondary" href="{% url 'drivex:user-login' %}?next={{ request.path }}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>

<div class="container content my-5">
  {% block main %}{% endblock %}
</div>

<footer class="footer bg-white shadow mt-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 text-center">
      <div class="mt-5">
        {% include 'drivex/parts/logo.html' %}
      </div>

      <ul class="mt-3 navbar-nav d-flex flex-row gap-4 justify-content-center">
        <li class="nav-item"><a href="{% url 'drivex:home' %}" class="nav-link">Home</a></li>
        <li class="nav-item"><a href="{% url 'drivex:car-list' %}" class="nav-link">Cars</a></li>
        <li class="nav-item"><a href="{% url 'drivex:brand-list' %}" class="nav-link">Brands</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Terms & Conditions</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Contact</a></li>
      </ul>

      
      {% comment %} <p class="menu">
        <a href="{% url 'drivex:home' %}">Home</a>
        <a href="{% url 'drivex:car-list' %}">Cars</a>
        <a href="{% url 'drivex:brand-list' %}">Brands</a>
        <a href="#">Terms & Conditions</a>
        <a href="#">Contact</a>
      </p> {% endcomment %}
      <ul class="mt-3 social navbar-nav d-flex flex-row justify-content-center gap-4">
        <li class="nav-item"><a class="d-flex justify-content-center align-items-center rounded-circle border border-primary text-decoration-none" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter"><i class="icon-twitter"></i></a></li>
        <li class="nav-item"><a class="d-flex justify-content-center align-items-center rounded-circle border border-primary text-decoration-none" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook"><i class="icon-facebook"></i></a></li>
        <li class="nav-item"><a class="d-flex justify-content-center align-items-center rounded-circle border border-primary text-decoration-none" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram"><i class="icon-instagram"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-md-12 text-center text-secondary">
      <p class="copyright">
        Copyright © Drivex 2023 All rights reserved 
      </p>
    </div>
  </div>
</div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

{% block extrajs %}{% endblock %}
</body>
</html>

drivex/templates/drivex/car_detail.html
{% extends 'drivex/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}DriveX - Cars{% endblock %}

{% block main %}

<section class="bg-white rounded mb-3 p-3">

  <div class="row justify-content-between">
    <div class="col-auto">
      <h3 class="">{{car.brand}} {{ car.name }}</h3>
    </div>
    <div class="col-auto">
      <img src="{{ car.brand.logo.url }}"
                class="object-fit-contain" alt="{{ car.brand }}" width="100" height="50">
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <img src="{% if car.image %}{{ car.image.url }}
                {% else %}{% static 'drivex/img/car.png' %}{% endif %}"
                class="object-fit-contain mb-3 ms-auto me-auto" alt="{{ car.name }}" height="160">

        <div class="row text-secondary text-center mb-2">
            <div class="col-2 p-0 d-flex flex-column ml-auto"><i class="icon-people"></i><span style="font-size: 0.625em">{{ car.passengers }}</span></div>
            <div class="col-2 p-0 d-flex flex-column"><i class="icon-door"></i><span style="font-size: 0.625em">{{ car.doors }}</span></div>
            <div class="col-2 p-0 d-flex flex-column"><i class="icon-suitcase"></i><span style="font-size: 0.625em">{{ car.boot_space }} L</span></div>
            <div class="col-3 p-0 d-flex flex-column"><i class="icon-canister"></i><span style="font-size: 0.625em">{{ car.consumption }} L/100km</span></div>
        </div>

    </div>
    <div class="col-md-8">

      <table class="table mb-5">
        <tr>
          <td>
          {% if car.power == "EL" %}
            Battery
          {% else %}
            Engine
          {% endif %}
              capacity</td>
          <td>{{ car.capacity }} 
            {% if car.power == "EL" %}
            kWh
            {% else %}
            L
            {% endif %}
          </td>
        </tr>
        <tr>
          <td>Transmission type</td>
          <td>{{ car.get_transmission_display }}</td>
        </tr>
        <tr>
          <td>Fuel type</td>
          <td>{{ car.get_power_display }}</td>
        </tr>
      </table>
    
      {% if car.features.exists %}
        <div class="text-secondary ms-2">
          <span class="text-dark">Features: </span>
        {% for feature in car.features.all %}          
          {{ feature }}{% if not forloop.last %},{% else %}{% endif %}
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
  <hr>
  <div class="row justify-content-between">
    <div class="col-auto">
      {% if car.num_reviews %}

        {% with car.rating as rt %}
        <span class="text-warning">
          <i class="icon-star{% if rt > 0 and rt < 1 %}-half{% elif rt < 1 %}-outline {% endif %}" aria-hidden="true"></i>
          <i class="icon-star{% if rt > 1 and rt < 2 %}-half{% elif rt < 2 %}-outline {% endif %}" aria-hidden="true"></i>
          <i class="icon-star{% if rt > 2 and rt < 3 %}-half{% elif rt < 3 %}-outline {% endif %}" aria-hidden="true"></i>
          <i class="icon-star{% if rt > 3 and rt < 4 %}-half{% elif rt < 4 %}-outline {% endif %}" aria-hidden="true"></i>
          <i class="icon-star{% if rt > 4 and rt < 5 %}-half{% elif rt < 5 %}-outline {% endif %}" aria-hidden="true"></i>
        </span>
        {{ rt|floatformat:1 }}
        {% endwith %}
        ({{ car.num_reviews }} review{{ car.num_reviews|pluralize }})
      {% endif %}
    </div>
    <div class="col-auto">
      <a href="{% url 'drivex:toggle-favorite' car_pk=car.id %}" class="btn btn-outline-primary ps-5 pe-5">
        {% if car in user.favorites.all %}
          Remove from
        {% else %}
          Add to
        {% endif %} favorites
      </a>
      <a class="btn btn-primary ps-5 pe-5">Book a car</a>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-6">
    {% include 'drivex/parts/messages.html' %}
      <h5>Reviews</h5>
      {% if user.is_authenticated %}
        
        {% if not user_rating %}
        <form class="review-form" action="{% url 'drivex:add-review' car_pk=car.id %}" method="post">
          {% csrf_token %}
          <fieldset class="star-rating">
          <legend class="fs-6">Your rating*</legend>
            <div class="mb-3">
              <input type="radio" name="rate" value="1" id="rating1" />
              <label for="rating1"><span>1</span></label>
              <input type="radio" name="rate" value="2" id="rating2" />
              <label for="rating2"><span>2</span></label>
              <input type="radio" name="rate" value="3" id="rating3" />
              <label for="rating3"><span>3</span></label>
              <input type="radio" name="rate" value="4" id="rating4" />
              <label for="rating4"><span>4</span></label>
              <input type="radio" name="rate" value="5" id="rating5" />
              <label for="rating5"><span>5</span></label>
            </div>
          </fieldset>
          {{ review_form|crispy }}
          <button type="submit" class="btn btn-outline-info">Add Review</button>
        </form>
        {% endif %}
        
      {% else %}
      <p>You have to log in to leave a review.</p>
      {% endif %}

        {% for review in reviews %}
          <hr>
          <div class="review-wrap position-relative">
            <div class="d-flex align-items-top">
              <span class="d-inline-block flex-shrink-0 overflow-hidden rounded-circle me-2" style="width: 30px; height: 30px">
                <img class="object-fit-cover" src="{{ review.user.profile.photo.url }}" width="100%" height="100%" />
              </span>
              <div>
                <span class="fw-bolder">{{ review.user }}</span> <span class="fst-italic fw-light">rated</span> {{ review.rate }} <i class="icon-star text-warning"></i>: <br> {{ review.text }}
              </div>
            </div>
            <div class="fst-italic fw-light text-end" style="font-size: .8em">{{ review.created|timesince }} ago</div>
            {% if review.user == user %}
              <button type="button" class="btn btn-sm btn-outline-secondary edit-btn" data-bs-toggle="modal" data-bs-target="#reviewModal">
                Edit <i class="icon-edit"></i>
              </button>
            {% endif %}
            
          </div>

        {% empty %}
        <p>Your review can be the first.</p>
        {% endfor %}

    </div>
  </div>
  
    
</section>


{% comment %} <section class="bg-white rounded p-3">
  <p>More cars by {{ car.brand }}:
    {% for c in car.brand.cars.all %}
      <a class="link-dark link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{{ c.url }}">{{ c|capfirst }}</a>{% if not forloop.last %},{% else %}{% endif %}
    {% endfor %}
  </p>
</section> {% endcomment %}


<!-- Modal -->
<div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form method="POST" action="{% url 'drivex:update-review' car_pk=car.id %}">
      {% csrf_token %}
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="reviewModalLabel">Editing review for {{ car }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <fieldset class="star-rating">
          <legend class="fs-6">Your rating*</legend>
            <div class="mb-3">
              <input type="radio" name="rate" value="1" id="rating1" 
              {% if user_rating == 1 %}
                checked
              {% endif %}
                 />
              <label for="rating1"><span>1</span></label>
              <input type="radio" name="rate" value="2" id="rating2" {% if user_rating == 2 %}
                checked
              {% endif %} />
              <label for="rating2"><span>2</span></label>
              <input type="radio" name="rate" value="3" id="rating3" {% if user_rating == 3 %}
                checked
              {% endif %} />
              <label for="rating3"><span>3</span></label>
              <input type="radio" name="rate" value="4" id="rating4" {% if user_rating == 4 %}
                checked
              {% endif %} />
              <label for="rating4"><span>4</span></label>
              <input type="radio" name="rate" value="5" id="rating5" {% if user_rating == 5 %}
                checked
              {% endif %} />
              <label for="rating5"><span>5</span></label>
            </div>
          </fieldset>
          {{ review_form|crispy }}

      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-outline-info">Save</button>
      </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

drivex/templates/drivex/order_list.html
{% extends 'drivex/profile_base.html' %}
{% load static %}

{% block title %}DriveX - Orders{% endblock %}

{% block profile_title %}Orders{% endblock %}

{% block content %}

  {% if orders %}

    <table class="table">
    <thead>
      <tr>
        <th scope="col">Created</th>
        <th scope="col">Car</th>
        <th scope="col">From - To</th>
        <th scope="col">Status</th>
        <th scope="col">Order number</th>
      </tr>
    </thead>
  
    
  
  {% for order in orders %}
    <tr>
      <td scope="row">{{ order.created|date:'d.m.Y H:i' }}</td>
      <td scope="row">{{ order.car }}</td>
      <td scope="row">{{ order.date_start|date:'d.m.Y' }}-{{ order.date_end|date:'d.m.Y' }}</td>
      <td scope="row">
      <span class="badge 
        {% if order.status == 'NW' %}
          text-bg-success
        {% endif %}

        {% if order.status == 'AC' %}
          text-bg-warning
        {% endif %}

        {% if order.status == 'CL' %}
          text-bg-secondary
        {% endif %}">

      {{ order.get_status_display }}
      </span>
      


      
      </td>
      <td scope="row">{{ order.number }}</td>
    </tr>
    
  {% endfor %}
    
</table>

  {% else %}
    <p>You have no ordres yet... <a href="{% url 'drivex:car-list' %}" class="link-dark">Choose a Car</a></p>
  {% endif %}

{% endblock %}